- hosts: rpi
  become: yes
  vars:
    pip_package: python3-pip
    pip_install_packages: #add in the docker Python library using the geerlingguy.pip role
      - name: docker
    docker_version_armv7: 5:19.03.1~3-0~raspbian-buster
    docker_version: "{{ docker_version_armv7 if 'armv7' in ansible_architecture else docker_version_arm64 }}"
    docker_install_recommends: true
    docker_install_compose: true
    docker_users:
      - pi
    docker_pip_executable: pip3

  roles:
    - geerlingguy.pip
    - geerlingguy.docker_arm