---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Update repo cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install Java 11
      apt:
        name: default-jdk
        state: present

    - name: Set JAVA_HOME variable
      lineinfile:
        path: /etc/environment
        line: JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"

#reboot so changes take affect
    - name: Check the uptime prior reboot
      shell: uptime
      register: UPTIME_PRE_REBOOT

    - debug: msg={{UPTIME_PRE_REBOOT.stdout}}

    - name: Reboot node and stop polling.
      shell: reboot
      async: 10 # Do not care for 10 sec
      poll: 0 # Fire & Forget