- hosts: servers
  become: yes
  vars:
    swap_file_path: /swapfile
    swap_file_size_mb: '128'
    swap_swappiness: '40'
    swap_file_state: present
    swap_file_create_command: "dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ swap_file_size_mb }}"

  roles:
    - geerlingguy.swap